name: newone
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.4
  shared_preferences: ^2.2.2
  sqflite: ^2.2.8+4
  path_provider: ^2.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  sqflite_common_ffi: ^2.3.4+4
  sqlite3_flutter_libs: ^0.5.31
  image_picker: ^1.1.2
  google_fonts: ^6.1.0
  pdf: ^3.10.7
  printing: ^5.12.0
  intl_phone_number_input: ^0.7.4
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/l10n/
    - lib/assets/crops/
    - lib/assets/fonts/NotoSansDevanagari-Regular.ttf
    - lib/assets/lottie/crop.json
    - lib/assets/lottie/Farm.json
    - lib/assets/lottie/report.json

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
